language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging 
  - docker build -t  test_travis_ci .
  - docker tag test_travis_ci YOUR_DOCKER_HUB/test_travis_ci_docker:latest #yep yep

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin #hiding my credentials 
  - docker push YOUR_DOCKER_HUB/test_travis_ci_docker
